on:
  push:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v2
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: joseGca11/inter-repository-workflows
            path: ./test

        - name: list file
          run: |
            ls