name: teste
on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: "teste"
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: joseGca11/inter-repository-workflows
          path: ./test
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: list file
        run: |
          ls
          ls test

      - name: Adding topology values
        run: |
          sed -i "/application:/r test/topology-resources/deployment_values.yaml" topology-resources/teste.yaml

      - name: show Values
        working-directory: topology-resources/
        run: cat teste.yaml

      - name: pod_name
        run: |
          echo "pod_name=hi" >> $GITHUB_ENV

      - name: print pod_name
        run: |
          echo ${{ env.pod_name }}
          echo $pod_name
          
