name: teste
on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: "teste"
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: joseGca11/inter-repository-workflows
          path: ./test
          ref: main

      - name: list file
        run: |
          ls test
